<AirNowPanel>:
    PanelBackground:
        _panelTitle: 'Air Quality'
    Label:
        text: app.CurrentConditions.AirQuality['AQI']
        font_name: 'fonts/Inter-Light.ttf'
        font_size: dp(48*app.scaleFactor)
        color: utils.rgba(app.CurrentConditions.AirQuality['Color'])
        size_hint: (92/262, 62/202)
        pos_hint: {'x': 4/262, 'y': 105/202}
    BoldMultilineField:
        text: app.CurrentConditions.AirQuality['Category']
        color: utils.rgba(app.CurrentConditions.AirQuality['Color'])
        font_size: dp((10 if len(app.CurrentConditions.AirQuality['Category']) > 15 else 13)*app.scaleFactor)
        size_hint: (96/262, 45/202)
        pos_hint: {'x': 2/262, 'y': 67/202}
    SmallField:
        text: app.CurrentConditions.AirQuality['Pollutant']
        size_hint: (96/262, 16/202)
        pos_hint: {'x': 2/262, 'y': 52/202}
    SmallMultilineField:
        text: app.CurrentConditions.AirQuality['Area'] + '\n' + app.CurrentConditions.AirQuality['Observed']
        size_hint: (96/262, 43/202)
        pos_hint: {'x': 2/262, 'y': 5/202}
        font_size: dp(10*app.scaleFactor)
    Image:
        source: app.CurrentConditions.AirQuality['Map']
        fit_mode: 'cover'
        size_hint: (155/262, 148/202)
        pos_hint: {'x': 102/262, 'y': 27/202}
    SmallField:
        text: str(app.config['AirNow']['Radius']) + ' mi radius · © OpenStreetMap'
        font_size: dp(7*app.scaleFactor)
        size_hint: (155/262, 17/202)
        pos_hint: {'x': 102/262, 'y': 5/202}

<AirNowButton>:
    PanelButton:
        text: 'AirNow'
        on_release: app.CurrentConditions.switchPanel(self)
